# Generated by Django 5.0.6 on 2024-07-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0004_alter_admin_login_id_alter_contact_id_alter_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/farmer_personal_photo/')),
                ('land_certificate', models.FileField(upload_to='static/farmer_personal_photo/')),
                ('adhar_card', models.ImageField(upload_to='static/farmer_personal_photo/')),
                ('terms_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
