# Generated by Django 5.0.6 on 2024-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0005_farmerdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_desc', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('payment', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='static/farmer_product/')),
                ('certificate', models.FileField(upload_to='static/farmer_product/')),
            ],
        ),
    ]
