# Generated by Django 5.0.6 on 2024-08-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0006_farmerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
