# Generated by Django 5.0.6 on 2024-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0007_alter_farmerproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='order_date',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='order_id',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
