# Generated by Django 5.0.6 on 2024-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0008_farmerproduct_order_date_farmerproduct_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
