# Generated by Django 5.0.6 on 2024-08-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0010_adminpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpayment',
            name='product_order_id',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
