# Generated by Django 5.0.6 on 2024-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0015_adminpayment_product_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminPayment',
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
