# Generated by Django 5.0.6 on 2024-08-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0016_delete_adminpayment_farmerproduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
