# Generated by Django 5.0.6 on 2024-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0018_alter_farmerproduct_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
