# Generated by Django 5.0.6 on 2024-08-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0021_alter_farmerproduct_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerproduct',
            name='razorpay_order_id',
        ),
    ]
