# Generated by Django 5.0.6 on 2024-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0022_remove_farmerproduct_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='razorpay_order_id',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100, unique=True),
        ),
    ]
