# Generated by Django 5.0.6 on 2024-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0026_alter_farmerproduct_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='created', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='status',
        ),
    ]
