# Generated by Django 5.0.6 on 2024-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0027_adminpayment_remove_farmerproduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='paymentorder_id',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
