# Generated by Django 5.0.6 on 2024-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0028_farmerproduct_paymentorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='order_id',
            field=models.CharField(default=False, max_length=100, unique=True),
        ),
    ]
