# Generated by Django 5.0.6 on 2024-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0029_alter_farmerproduct_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=255)),
                ('uemail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=255)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
