# Generated by Django 5.0.6 on 2024-09-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HarvestHUB', '0031_userpayment_price_userpayment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
